import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  introSidebar: [{type: 'autogenerated', dirName: '.'}],
  examples: [{
    type: 'category',
    label: 'Examples',
    items: [
      {
        type: 'doc',
        id: 'examples/basic',
        label: 'Basic example',
      },
      {
        type: 'doc',
        id: 'examples/complex',
        label: 'Complex example ',
      }
    ]
  }],
};

export default sidebars;
